### ISSUE TITLE
Package not working after upgrading to 3.1.0

### ISSUE THREAD

**Issue by nodegin** [swiftcarrot/color-fns#148]
<img width="356" alt="Screenshot 2020-06-22 at 3 07 57 AM" src="https://user-images.githubusercontent.com/8536244/85232931-ab64d580-b435-11ea-8e8f-32a57b9014fe.png">
<img width="868" alt="Screenshot 2020-06-22 at 3 08 06 AM" src="https://user-images.githubusercontent.com/8536244/85232934-adc72f80-b435-11ea-8f31-b86291658953.png">

**Comment by wangzuo** [comment]
made a patch in `3.1.1`
