### ISSUE TITLE
Wrong hsv2rgb result if h=360

### ISSUE THREAD

**Issue by omgovich** [swiftcarrot/color-fns#149]
Hi! First of all, thank you for your work!
The library is super lightweight and fast. I really like it!

Just found a small bug: `hsv2rgb` method returns the wrong result if `h` is `360`.

Example:
```js 
hsv2rgb({ h: 360, s: 50, v: 50 }) // {r: NaN, g: NaN, b: NaN}
```

`360` is a valid value:
![image](https://user-images.githubusercontent.com/206567/89466249-2252f500-d77c-11ea-9791-679d612a75d8.png)

**Comment by wangzuo** [comment]
Thanks, will check.

**Comment by omgovich** [comment]
Thanks a lot! ♥️
